### PR TITLE
Add Actions for Moving Spaces and Changing Brightness for System

### PR DESCRIPTION
**Pull request by ejwill**
Added System functionality to move between "Spaces" (desktops) and increase/decrease brightness

### CODE REVIEW

**Comment by larsblumberg** [comment]
Thank you for your Pull Request!

Can you please
- Make every AppleScript a one-liner, e.g. `tell application "System Events" to keycode 113`
- Rename the space actions to `Move Left a Space` and `Move Right a Space`?
- Squash all commits into a single commit

**Comment by ejwill** [comment]
@larsblumberg I get a compile error when I try to save the files as one line "expected end of line but found property"

I have renamed the files.  

It appears you can squash the commits when merging the pull request as of March [https://help.github.com/articles/about-pull-request-merge-squashing/](https://help.github.com/articles/about-pull-request-merge-squashing/).  Do you still want me to squash the commits?

**Comment by larsblumberg** [comment]
Oh, thanks, I wasn't aware of it. I will squash then when merging right now. Thanks again for your Pull Requests!

**Comment by ejwill** [comment]
@larsblumberg, no problem.  I'll try to work on some others.  Is there something I need to do to make them show up in the drop-down for actions or is that something you take care of?

**Comment by larsblumberg** [comment]
When you restart your Nuimo app, it will download the latest actions.

**Comment by ejwill** [comment]
@larsblumberg don't they have to be script files for it to work?  I've been uploading applescript text files so the text shows up on github

**Comment by larsblumberg** [comment]
Thanks – I've renamed the file extension to `.scpt` now. You can also save to `.scpt` files in text format.

**Pull request merged**
