### PR TITLE
Add actions for Sonos.

### PR DESCRIPTION
**Pull request by melwin**
Actions for Sonos using generic tell process.

### CODE REVIEW

**Comment by larsblumberg** [comment]
Awesome – will try them out and merge

**Comment by melwin** [comment]
Just realized the Next/Prev track actions don't work. Play/Pause works fine, but for Next/Prev it clicks the right button in the UI but nothing happens. They must detect the mouse down event or something else that is missing when using AppleScript this way. I will see what I can find.

**Comment by melwin** [comment]
It seems like Command+Left/Right works to change track. Changed the action to use this instead.

**Comment by melwin** [comment]
@larsblumberg Let me know if you want me to change these actions to use key code as well for the arrows.

**Comment by larsblumberg** [comment]
@melwin yeah let's use key codes instead of ASCII characters – so we stay consistent

**Comment by melwin** [comment]
Ok, updated.

**Comment by larsblumberg** [comment]
Thanks a lot!

**Pull request merged**
